# Generated by Django 2.0 on 2020-03-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comment_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complainant', models.CharField(max_length=18)),
                ('subject', models.CharField(max_length=120)),
                ('post_url', models.URLField(default='')),
                ('content', models.TextField(max_length=9999)),
                ('status', models.CharField(choices=[('p', 'processing'), ('ps', 'processed'), ('cps', 'complaint process succeed')], default='p', max_length=32)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
