# Generated by Django 2.2.3 on 2019-09-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favourite_posts',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favourite_posts',
            field=models.ManyToManyField(to='core.Post'),
        ),
    ]
