# Generated by Django 2.0 on 2020-03-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_complaints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='content',
            field=models.TextField(default='', max_length=9999),
        ),
    ]
