# Generated by Django 2.2.3 on 2019-09-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190922_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favourite_posts',
            field=models.ManyToManyField(blank=True, to='core.Post'),
        ),
    ]
