# Generated by Django 2.0 on 2020-03-19 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200319_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaints',
            old_name='content',
            new_name='contents',
        ),
    ]
