# Generated by Django 2.0 on 2020-03-19 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200319_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaints',
            old_name='contents',
            new_name='content',
        ),
    ]
