# Generated by Django 2.2.3 on 2019-09-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190928_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(help_text='Eg:django,django1,django2,...', max_length=999, verbose_name='Tags'),
        ),
    ]
