# Generated by Django 2.2.3 on 2019-09-30 19:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190929_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, help_text='Meta Description Tag.', max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(unique=True, verbose_name='Content'),
        ),
    ]
