# Generated by Django 2.2.3 on 2019-10-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190930_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Title'),
        ),
    ]
