# Generated by Django 2.2.3 on 2019-10-06 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20191002_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favourite_posts',
        ),
    ]
