# Generated by Django 2.2.3 on 2019-11-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_userprofile_favourite_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favourite_comments',
            field=models.ManyToManyField(to='core.Comment'),
        ),
    ]
