# Generated by Django 2.0 on 2020-02-15 13:03

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, unique=True, verbose_name='Title')),
                ('content', ckeditor.fields.RichTextField(unique=True, verbose_name='Content')),
                ('description', models.TextField(blank=True, help_text='Meta Description Tag.', max_length=500, null=True, verbose_name='Description')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Image')),
                ('tags', models.CharField(help_text='Eg:django,django1,django2,...', max_length=999, verbose_name='Tags')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('slug', models.SlugField(editable=False)),
                ('number_of_favourite', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.Category')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
