# Generated by Django 2.0 on 2020-02-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comment_post'),
        ('post', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favourite_comments',
            field=models.ManyToManyField(to='core.Comment'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favourite_posts',
            field=models.ManyToManyField(to='post.Post'),
        ),
    ]
